services:
  database:
    container_name: "restaurant-reservation-db"
    image: "postgres:16.0-alpine3.18"
    volumes:
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "5432:5432"
